title: Nur eine fusselige Baustelle
author: fussldrach
email: greebo173@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  There's nothing awesome about "my new site". You can just start to dampen down your 
  excitement (or your sarcasm - whichever)
  Apparently this does something to the "head"-Section in the index.html. 
  Now that is a file I would like to access! But I guess I'll better go on tinkering with this here while I am newbie-status
  "You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description."

# social links
github_username:  fussldrach

show_excerpts: true # set to false to remove excerpts on the homepage
